public class ZipcodeClass {
	
    public string postal_code{get;set;}
    public string country_code{get;set;}
    public string latitude{get;set;}
    public string longitude{get;set;}
    public string city{get;set;}
    public string state{get;set;}
    public string city_en{get;set;}
    public string state_en{get;set;}
    public string state_code{get;set;}
    public string province{get;set;}
    public string province_code{get;set;}
    
}